'use strict';
// ---------- Static game data ----------
let LANG = 'en';
const L = o => (o && typeof o === 'object') ? (o[LANG] || o.en) : o;

// Time: game minutes per real second
const MIN_PER_SEC = 2.5;

// c: raw | ref | food | med
const ITEMS = {
  plastic:    { n: { en: 'Plastic Bottles', tr: 'Plastik Şişe' }, i: '🧴', w: .2, p: 2, c: 'raw' },
  paper:      { n: { en: 'Cardboard', tr: 'Karton' }, i: '📦', w: .3, p: 1, c: 'raw' },
  can:        { n: { en: 'Alu Cans', tr: 'Alüminyum Kutu' }, i: '🥤', w: .15, p: 2, c: 'raw' },
  glass:      { n: { en: 'Glass', tr: 'Cam' }, i: '🍾', w: .4, p: 1, c: 'raw' },
  scrap:      { n: { en: 'Scrap Metal', tr: 'Hurda Demir' }, i: '🔩', w: .8, p: 3, c: 'raw' },
  copper:     { n: { en: 'Copper Wire', tr: 'Bakır Kablo' }, i: '🔌', w: .4, p: 8, c: 'raw' },
  rubber:     { n: { en: 'Rubber', tr: 'Kauçuk' }, i: '⚫', w: .6, p: 3, c: 'raw' },
  ewaste:     { n: { en: 'Circuit Boards', tr: 'Devre Kartı' }, i: '💾', w: .3, p: 10, c: 'raw' },
  battery:    { n: { en: 'Old Batteries', tr: 'Eski Akü' }, i: '🔋', w: .7, p: 9, c: 'raw' },
  motor:      { n: { en: 'Electric Motor', tr: 'Elektrik Motoru' }, i: '⚙️', w: 2, p: 25, c: 'raw' },
  magnet:     { n: { en: 'Neodymium Magnet', tr: 'Neodim Mıknatıs' }, i: '🧲', w: .2, p: 45, c: 'raw' },
  gold:       { n: { en: 'Gold Chip', tr: 'Altın Çip' }, i: '✨', w: .05, p: 90, c: 'raw' },

  pellets:    { n: { en: 'Plastic Pellets', tr: 'Plastik Granül' }, i: '⚪', w: .3, p: 6, c: 'ref' },
  bale:       { n: { en: 'Paper Bale', tr: 'Kağıt Balya' }, i: '🗞️', w: .6, p: 5, c: 'ref' },
  alu:        { n: { en: 'Aluminum Ingot', tr: 'Alüminyum Külçe' }, i: '⬜', w: .4, p: 10, c: 'ref' },
  steel:      { n: { en: 'Steel Plate', tr: 'Çelik Levha' }, i: '⬛', w: 2, p: 14, c: 'ref' },
  cullet:     { n: { en: 'Glass Cullet', tr: 'Cam Kırığı' }, i: '💎', w: .6, p: 4, c: 'ref' },
  cuingot:    { n: { en: 'Copper Ingot', tr: 'Bakır Külçe' }, i: '🟧', w: .7, p: 26, c: 'ref' },
  crumb:      { n: { en: 'Rubber Crumb', tr: 'Kauçuk Granül' }, i: '🟤', w: .9, p: 9, c: 'ref' },
  components: { n: { en: 'Components', tr: 'Elektronik Parça' }, i: '🎛️', w: .2, p: 22, c: 'ref' },
  lithium:    { n: { en: 'Lithium Cells', tr: 'Lityum Hücre' }, i: '⚡', w: .3, p: 20, c: 'ref' },

  water:    { n: { en: 'Water Bottle', tr: 'Su Şişesi' }, i: '💧', w: .5, p: 2, buy: 5, c: 'food', eat: { thirst: 35 } },
  dirty:    { n: { en: 'Dirty Water', tr: 'Kirli Su' }, i: '🚱', w: .5, p: 0, c: 'food', eat: { thirst: 25 }, sick: .35 },
  bread:    { n: { en: 'Bread', tr: 'Ekmek' }, i: '🍞', w: .3, p: 2, buy: 6, c: 'food', eat: { hunger: 22, thirst: -3 } },
  canned:   { n: { en: 'Canned Beans', tr: 'Konserve Fasulye' }, i: '🥫', w: .4, p: 4, buy: 12, c: 'food', eat: { hunger: 38 } },
  scraps:   { n: { en: 'Food Scraps', tr: 'Yemek Artığı' }, i: '🍌', w: .2, p: 0, c: 'food', eat: { hunger: 12 }, sick: .3 },
  veg:      { n: { en: 'Fresh Veggies', tr: 'Taze Sebze' }, i: '🥕', w: .3, p: 3, c: 'food', eat: { hunger: 25, thirst: 8 } },
  stew:     { n: { en: 'Hot Stew', tr: 'Sıcak Güveç' }, i: '🍲', w: .5, p: 8, c: 'food', eat: { hunger: 55, thirst: 15, hp: 10 } },
  energy:   { n: { en: 'Energy Drink', tr: 'Enerji İçeceği' }, i: '🧃', w: .3, p: 3, buy: 10, c: 'food', eat: { energy: 30, thirst: 8 } },
  bandage:  { n: { en: 'Bandage', tr: 'Bandaj' }, i: '🩹', w: .1, p: 5, buy: 15, c: 'med', eat: { hp: 25 } },
  medicine: { n: { en: 'Medicine', tr: 'İlaç' }, i: '💊', w: .1, p: 8, buy: 25, c: 'med', eat: { hp: 10 }, cure: true },
};
const SHOP_ITEMS = ['water', 'bread', 'canned', 'energy', 'bandage', 'medicine'];

// Tools, gear, bags, carts. kind: tool|gear|bag|cart
const CRAFT = {
  crowbar:    { kind: 'tool', i: '⛏️', n: { en: 'Crowbar', tr: 'Levye' }, cost: { scrap: 5 }, cash: 0, dmg: 14,
                d: { en: 'Pry open vending machines, appliances and doors.', tr: 'Otomat, beyaz eşya ve kapıları kanırt.' } },
  gloves:     { kind: 'gear', i: '🧤', n: { en: 'Work Gloves', tr: 'İş Eldiveni' }, cost: { rubber: 3, plastic: 4 }, cash: 5,
                d: { en: '+20% search speed.', tr: '+%20 arama hızı.' } },
  backpack:   { kind: 'bag', cap: 25, i: '🎒', n: { en: 'Backpack (25 kg)', tr: 'Sırt Çantası (25 kg)' }, cost: { plastic: 12, rubber: 4 }, cash: 25,
                d: { en: 'Carry 25 kg instead of 12.', tr: '12 yerine 25 kg taşı.' } },
  wrench:     { kind: 'tool', i: '🔧', n: { en: 'Wrench', tr: 'İngiliz Anahtarı' }, cost: { steel: 2, scrap: 4 }, cash: 10, dmg: 12,
                d: { en: 'Dismantle cars, bikes and pipes.', tr: 'Araba, bisiklet ve boruları sök.' } },
  cart:       { kind: 'cart', cap: 30, spd: -.08, i: '🛒', n: { en: 'Shopping Cart (+30 kg)', tr: 'Market Arabası (+30 kg)' }, cost: { steel: 4, crumb: 2 }, cash: 40,
                d: { en: '+30 kg capacity, slightly slower.', tr: '+30 kg kapasite, biraz yavaşlatır.' } },
  cutters:    { kind: 'tool', i: '✂️', n: { en: 'Bolt Cutters', tr: 'Cıvata Makası' }, cost: { steel: 4, alu: 2 }, cash: 60, dmg: 10,
                d: { en: 'Cut cable spools and the Industrial gate lock.', tr: 'Kablo makaralarını ve Sanayi kapısının kilidini kes.' } },
  boots:      { kind: 'gear', i: '🥾', n: { en: 'Work Boots', tr: 'İş Botu' }, cost: { crumb: 4, pellets: 3 }, cash: 40,
                d: { en: '+10% move speed.', tr: '+%10 hareket hızı.' } },
  respirator: { kind: 'gear', i: '😷', n: { en: 'Respirator', tr: 'Gaz Maskesi' }, cost: { pellets: 4, crumb: 3, cullet: 2 }, cash: 80,
                d: { en: 'Breathe safely in the toxic E-Waste Dump.', tr: 'Zehirli E-Atık Çöplüğünde güvenle nefes al.' } },
  hikingpack: { kind: 'bag', cap: 40, i: '🏕️', n: { en: 'Hiking Pack (40 kg)', tr: 'Kamp Çantası (40 kg)' }, cost: { pellets: 8, crumb: 4, alu: 4 }, cash: 150,
                d: { en: 'Carry 40 kg.', tr: '40 kg taşı.' } },
  headlamp:   { kind: 'gear', i: '🔦', n: { en: 'Headlamp', tr: 'Kafa Lambası' }, cost: { battery: 2, cuingot: 2, cullet: 2 }, cash: 100,
                d: { en: 'Big light radius. Essential in dark Downtown.', tr: 'Geniş ışık. Karanlık Şehir Merkezi için şart.' } },
  grinder:    { kind: 'tool', i: '💿', n: { en: 'Angle Grinder', tr: 'Avuç Taşlama' }, cost: { motor: 2, steel: 6, lithium: 2 }, cash: 250, dmg: 22,
                d: { en: 'Cut transformers, servers, ATMs and the Downtown barricade.', tr: 'Trafo, sunucu, ATM ve Merkez barikatını kes.' } },
  trike:      { kind: 'cart', cap: 60, spd: .12, i: '🚲', n: { en: 'Cargo Trike (+60 kg)', tr: 'Yük Bisikleti (+60 kg)' }, cost: { steel: 10, alu: 6, crumb: 6, motor: 1, lithium: 2 }, cash: 600,
                d: { en: '+60 kg and +12% speed. The scavenger dream.', tr: '+60 kg ve +%12 hız. Hurdacının rüyası.' } },
};
const TOOL_ORDER = ['crowbar', 'wrench', 'cutters', 'grinder'];

// Base structures. m: machine recipes
const BUILDS = {
  bed:        { i: '🛏️', n: { en: 'Mattress Bed', tr: 'Yataklı Döşek' }, cost: { paper: 8, plastic: 6 }, cash: 10,
                d: { en: 'Sleep restores full energy (cardboard: 70%).', tr: 'Uyku tüm enerjiyi yeniler (karton: %70).' } },
  rainbarrel: { i: '🛢️', n: { en: 'Rain Barrel', tr: 'Yağmur Varili' }, cost: { plastic: 10, scrap: 2 }, cash: 0,
                d: { en: '+2 water every morning, +4 after rain.', tr: 'Her sabah +2 su, yağmurdan sonra +4.' } },
  shredder:   { i: '🧴', n: { en: 'Plastic Shredder', tr: 'Plastik Kırıcı' }, cost: { scrap: 6 }, cash: 30,
                d: { en: 'Plastic → Pellets', tr: 'Plastik → Granül' }, m: [{ in: { plastic: 2 }, out: { pellets: 1 }, t: 10 }] },
  crusher:    { i: '🍾', n: { en: 'Glass Crusher', tr: 'Cam Kırıcı' }, cost: { scrap: 8 }, cash: 30,
                d: { en: 'Glass → Cullet', tr: 'Cam → Cam Kırığı' }, m: [{ in: { glass: 2 }, out: { cullet: 1 }, t: 8 }] },
  baler:      { i: '🗞️', n: { en: 'Paper Baler', tr: 'Kağıt Balya Makinesi' }, cost: { scrap: 6, plastic: 6 }, cash: 20,
                d: { en: 'Cardboard → Bales', tr: 'Karton → Balya' }, m: [{ in: { paper: 3 }, out: { bale: 1 }, t: 10 }] },
  smelter:    { i: '🔥', n: { en: 'Scrap Smelter', tr: 'Hurda Ocağı' }, cost: { scrap: 12 }, cash: 50,
                d: { en: 'Cans → Aluminum, Scrap → Steel', tr: 'Kutu → Alüminyum, Hurda → Çelik' },
                m: [{ in: { scrap: 3 }, out: { steel: 1 }, t: 22 }, { in: { can: 3 }, out: { alu: 1 }, t: 18 }] },
  tirecutter: { i: '⚫', n: { en: 'Rubber Cutter', tr: 'Kauçuk Kesici' }, cost: { steel: 3, scrap: 4 }, cash: 40,
                d: { en: 'Rubber → Crumb', tr: 'Kauçuk → Granül' }, m: [{ in: { rubber: 2 }, out: { crumb: 1 }, t: 14 }] },
  stripper:   { i: '🔌', n: { en: 'Wire Stripper', tr: 'Kablo Soyucu' }, cost: { steel: 3, crumb: 1 }, cash: 80,
                d: { en: 'Copper Wire → Copper Ingot', tr: 'Bakır Kablo → Bakır Külçe' }, m: [{ in: { copper: 2 }, out: { cuingot: 1 }, t: 18 }] },
  filter:     { i: '🚰', n: { en: 'Water Filter', tr: 'Su Filtresi' }, cost: { cullet: 3, pellets: 3 }, cash: 30,
                d: { en: 'Dirty Water → Clean Water', tr: 'Kirli Su → Temiz Su' }, m: [{ in: { dirty: 1 }, out: { water: 1 }, t: 6 }] },
  stove:      { i: '🍲', n: { en: 'Scrap Stove', tr: 'Hurda Soba' }, cost: { steel: 3, scrap: 4 }, cash: 25,
                d: { en: 'Cook hot stew (+hunger, +health).', tr: 'Sıcak güveç pişir (+tokluk, +sağlık).' },
                m: [{ in: { canned: 1, water: 1 }, out: { stew: 1 }, t: 10 }, { in: { scraps: 2, dirty: 1 }, out: { stew: 1 }, t: 15 }] },
  garden:     { i: '🥕', n: { en: 'Rooftop Garden', tr: 'Bostan' }, cost: { bale: 2, pellets: 4 }, cash: 40,
                d: { en: '+2 fresh veggies every morning.', tr: 'Her sabah +2 taze sebze.' } },
  lock:       { i: '🔒', n: { en: 'Steel Gate & Lock', tr: 'Çelik Kapı & Kilit' }, cost: { steel: 4, scrap: 6 }, cash: 50,
                d: { en: 'Stops night thieves from raiding your stash.', tr: 'Gece hırsızlarının deponu yağmalamasını engeller.' } },
  ebench:     { i: '🎛️', n: { en: 'E-Waste Bench', tr: 'E-Atık Tezgahı' }, cost: { cuingot: 3, steel: 4, pellets: 4 }, cash: 150,
                d: { en: 'Boards → Components (+gold), Batteries → Lithium', tr: 'Kart → Parça (+altın), Akü → Lityum' },
                m: [{ in: { ewaste: 1 }, out: { components: 1 }, t: 20, bonus: ['gold', .08] }, { in: { battery: 1 }, out: { lithium: 1 }, t: 24 }] },
  solar:      { i: '☀️', n: { en: 'Solar Panels', tr: 'Güneş Paneli' }, cost: { cullet: 6, cuingot: 3, alu: 4, lithium: 2 }, cash: 300,
                d: { en: 'All machines +30% speed. Lights up the base.', tr: 'Tüm makineler +%30 hız. Üssü aydınlatır.' } },
};
const MACHINE_KEYS = Object.keys(BUILDS).filter(k => BUILDS[k].m);
const MACHINE_UP = [null, { cash: 120, cost: { steel: 3 } }, { cash: 400, cost: { steel: 6, cuingot: 3 } }, { cash: 1200, cost: { components: 4, lithium: 3 } }];
const MACHINE_SPD = [0, 1, 1.6, 2.4, 3.5];

// Scavenge nodes
const NODES = {
  trashbag:    { n: { en: 'Trash Bag', tr: 'Çöp Poşeti' }, t: 2, xp: 2, resp: 12, col: 1,
                 loot: [['plastic', 1, 3, 1], ['paper', 0, 2, .7], ['can', 1, 2, .45], ['glass', 1, 1, .2], ['scraps', 1, 1, .18], ['water', 1, 1, .04]] },
  dumpster:    { n: { en: 'Dumpster', tr: 'Çöp Konteyneri' }, t: 3.5, xp: 4, resp: 16, col: 1.3,
                 loot: [['paper', 1, 4, .9], ['plastic', 1, 3, .8], ['can', 1, 3, .6], ['glass', 1, 2, .45], ['scrap', 1, 2, .45], ['scraps', 1, 1, .2], ['ewaste', 1, 1, .06], ['canned', 1, 1, .08], ['copper', 1, 1, .05]] },
  cardboard:   { n: { en: 'Cardboard Pile', tr: 'Karton Yığını' }, t: 1.6, xp: 1, resp: 10, loot: [['paper', 2, 5, 1]] },
  canpile:     { n: { en: 'Can Pile', tr: 'Kutu Yığını' }, t: 1.6, xp: 1, resp: 12, loot: [['can', 2, 4, 1], ['plastic', 1, 1, .3]] },
  bottles:     { n: { en: 'Bottle Crate', tr: 'Şişe Kasası' }, t: 1.8, xp: 1, resp: 12, loot: [['glass', 2, 4, 1], ['plastic', 1, 2, .3]] },
  vending:     { n: { en: 'Vending Machine', tr: 'Otomat' }, t: 4.5, tool: 'crowbar', xp: 8, resp: 72, col: 1.5, cash: [4, 18, 1],
                 loot: [['water', 1, 2, .75], ['canned', 1, 1, .45], ['bread', 1, 1, .35], ['energy', 1, 1, .35], ['scrap', 1, 3, .8], ['glass', 1, 1, .5], ['copper', 1, 1, .3]] },
  bike:        { n: { en: 'Bike Wreck', tr: 'Bisiklet Enkazı' }, t: 3.5, tool: 'wrench', xp: 5, resp: 48, loot: [['scrap', 2, 4, 1], ['rubber', 1, 3, 1]] },
  fountain:    { n: { en: 'Public Fountain', tr: 'Çeşme' }, t: 1.2, xp: 0, water: true },
  fridge:      { n: { en: 'Old Fridge', tr: 'Eski Buzdolabı' }, t: 5, tool: 'crowbar', xp: 8, resp: 48,
                 loot: [['scrap', 3, 6, 1], ['copper', 1, 2, .7], ['plastic', 1, 3, .8], ['motor', 1, 1, .25], ['canned', 1, 1, .1], ['scraps', 1, 1, .2]] },
  washer:      { n: { en: 'Washing Machine', tr: 'Çamaşır Makinesi' }, t: 5, tool: 'crowbar', xp: 8, resp: 48,
                 loot: [['scrap', 3, 5, 1], ['motor', 1, 1, .4], ['rubber', 1, 2, .8], ['copper', 1, 1, .5]] },
  tv:          { n: { en: 'Broken TV', tr: 'Bozuk Televizyon' }, t: 3, xp: 5, resp: 36,
                 loot: [['glass', 2, 3, 1], ['ewaste', 1, 2, .8], ['copper', 1, 1, .6], ['plastic', 1, 2, .7]] },
  yardbox:     { n: { en: 'Yard Sale Box', tr: 'Eskici Kutusu' }, t: 2.5, xp: 4, resp: 36, col: 4, cash: [1, 6, .5],
                 loot: [['paper', 1, 2, .8], ['plastic', 1, 2, .6], ['battery', 1, 1, .15], ['bread', 1, 1, .1], ['rubber', 1, 1, .3]] },
  car:         { n: { en: 'Car Wreck', tr: 'Araba Enkazı' }, t: 7, tool: 'wrench', xp: 14, resp: 96, col: 1.5,
                 loot: [['scrap', 6, 10, 1], ['rubber', 2, 4, 1], ['battery', 1, 1, .6], ['copper', 1, 3, .8], ['glass', 1, 2, .7], ['motor', 1, 1, .15]] },
  house:       { n: { en: 'Abandoned House', tr: 'Terk Edilmiş Ev' }, t: 9, tool: 'crowbar', xp: 25, resp: 168, col: 6, cash: [5, 30, .8], door: true,
                 loot: [['canned', 1, 2, .8], ['water', 1, 2, .7], ['ewaste', 1, 2, .6], ['copper', 1, 3, .6], ['bandage', 1, 1, .35], ['battery', 1, 1, .3], ['medicine', 1, 1, .15]] },
  pipes:       { n: { en: 'Pipe Stack', tr: 'Boru Yığını' }, t: 4, tool: 'wrench', xp: 6, resp: 36, loot: [['scrap', 4, 7, 1], ['copper', 1, 3, .45]] },
  drums:       { n: { en: 'Metal Drums', tr: 'Metal Variller' }, t: 3, tool: 'crowbar', xp: 4, resp: 24, loot: [['scrap', 2, 4, 1], ['plastic', 1, 2, .3]] },
  cable:       { n: { en: 'Cable Spool', tr: 'Kablo Makarası' }, t: 5, tool: 'cutters', xp: 12, resp: 48, loot: [['copper', 4, 8, 1], ['rubber', 1, 2, .7]] },
  forklift:    { n: { en: 'Forklift Wreck', tr: 'Forklift Enkazı' }, t: 9, tool: 'wrench', xp: 18, resp: 120,
                 loot: [['scrap', 8, 14, 1], ['motor', 1, 2, .8], ['battery', 1, 2, .8], ['rubber', 2, 3, 1]] },
  crate:       { n: { en: 'Motor Crate', tr: 'Motor Sandığı' }, t: 6, tool: 'crowbar', xp: 10, resp: 72, col: 1.5,
                 loot: [['motor', 1, 2, .9], ['copper', 2, 3, .8], ['scrap', 2, 3, 1], ['paper', 1, 2, .5]] },
  transformer: { n: { en: 'Transformer Box', tr: 'Trafo Kutusu' }, t: 10, tool: 'grinder', xp: 30, resp: 120,
                 loot: [['copper', 10, 16, 1], ['scrap', 6, 10, 1], ['magnet', 1, 1, .3]] },
  heap:        { n: { en: 'E-Waste Heap', tr: 'E-Atık Yığını' }, t: 4, xp: 6, resp: 24,
                 loot: [['ewaste', 2, 4, 1], ['plastic', 1, 3, .8], ['copper', 1, 2, .5], ['battery', 1, 1, .3], ['glass', 1, 1, .3], ['gold', 1, 1, .025]] },
  crt:         { n: { en: 'CRT Monitors', tr: 'Tüplü Monitörler' }, t: 3.5, xp: 5, resp: 24, loot: [['glass', 3, 5, 1], ['ewaste', 1, 1, .7], ['copper', 1, 2, .7]] },
  batteries:   { n: { en: 'Battery Pile', tr: 'Akü Yığını' }, t: 3, xp: 5, resp: 36, loot: [['battery', 2, 4, 1]] },
  server:      { n: { en: 'Server Rack', tr: 'Sunucu Kabini' }, t: 9, tool: 'grinder', xp: 28, resp: 96, col: 2,
                 loot: [['ewaste', 5, 8, 1], ['copper', 3, 5, 1], ['magnet', 1, 1, .4], ['gold', 1, 1, .3], ['can', 2, 3, .6]] },
  shop:        { n: { en: 'Abandoned Shop', tr: 'Terk Edilmiş Dükkan' }, t: 8, tool: 'crowbar', xp: 22, resp: 120, col: 5, cash: [10, 40, 1], door: true,
                 loot: [['canned', 2, 3, 1], ['water', 2, 3, 1], ['energy', 1, 2, .7], ['bandage', 1, 1, .6], ['medicine', 1, 1, .3], ['plastic', 2, 4, .8]] },
  atm:         { n: { en: 'Old ATM', tr: 'Eski ATM' }, t: 12, tool: 'grinder', xp: 35, resp: 168, cash: [60, 220, 1], door: true,
                 loot: [['ewaste', 1, 2, 1], ['scrap', 3, 5, 1]] },
  office:      { n: { en: 'Office Desk', tr: 'Ofis Masası' }, t: 5, tool: 'crowbar', xp: 10, resp: 48, col: 4,
                 loot: [['ewaste', 2, 3, 1], ['paper', 3, 5, 1], ['plastic', 1, 2, .6], ['battery', 1, 1, .3], ['magnet', 1, 1, .1]] },
  hdd:         { n: { en: 'Hard Drive Pile', tr: 'Hard Disk Yığını' }, t: 5, xp: 10, resp: 48, loot: [['magnet', 1, 2, .65], ['ewaste', 1, 2, .9], ['can', 1, 2, .7]] },
  pile:        { n: { en: 'Dropped Loot', tr: 'Yere Düşen Ganimet' }, t: .4, xp: 0 },
  dump:        { n: { en: 'Illegal Dump', tr: 'Kaçak Döküm' }, t: 5, xp: 25, col: 6 },
};

const DISTRICTS = {
  center: { n: { en: 'Backstreets', tr: 'Arka Sokaklar' }, tier: 0, col: '#c9a86a',
            nodes: { trashbag: 6, dumpster: 3, cardboard: 3, canpile: 2, bottles: 2, vending: 1.2, bike: 1 }, perBlock: [5, 7], cars: .15, broken: .3 },
  north:  { n: { en: 'Old Suburbs', tr: 'Eski Banliyö' }, tier: 1, col: '#8fbf6a',
            nodes: { trashbag: 4, dumpster: 2, cardboard: 1, fridge: 2, washer: 2, tv: 2, yardbox: 2.2, bike: 1, vending: .6 }, perBlock: [5, 7], cars: .5, broken: .2, doors: ['house', 1.4] },
  east:   { n: { en: 'Rust Belt Industrial', tr: 'Paslı Sanayi' }, tier: 2, col: '#e08a4a',
            nodes: { pipes: 3, drums: 3, cable: 3, crate: 2, forklift: 1, dumpster: 1, transformer: 1, fridge: 1 }, perBlock: [5, 7], cars: .6, broken: .45 },
  south:  { n: { en: 'E-Waste Dump', tr: 'E-Atık Çöplüğü' }, tier: 3, col: '#9ad14f',
            nodes: { heap: 5, crt: 3, batteries: 2, tv: 2, fridge: 1, washer: 1, server: 1 }, perBlock: [7, 9], cars: .3, broken: .6 },
  west:   { n: { en: 'Old Downtown', tr: 'Eski Şehir Merkezi' }, tier: 4, col: '#8aa0d8',
            nodes: { office: 3, hdd: 2, vending: 2, server: 1, trashbag: 2, dumpster: 1, tv: 1 }, perBlock: [5, 7], cars: .6, broken: .8, doors: ['shop', 1, 'atm', .4] },
};

const COLLECTIBLES = {
  coin:     { d: 'center', i: '🪙', n: { en: 'Ottoman Coin', tr: 'Osmanlı Sikkesi' }, v: 60 },
  duck:     { d: 'center', i: '🦆', n: { en: 'Rubber Duck', tr: 'Lastik Ördek' }, v: 25 },
  comic:    { d: 'center', i: '📕', n: { en: 'Rare Comic', tr: 'Nadir Çizgi Roman' }, v: 45 },
  cassette: { d: 'center', i: '📼', n: { en: 'Mixtape Cassette', tr: 'Karışık Kaset' }, v: 30 },
  globe:    { d: 'north', i: '🔮', n: { en: 'Snow Globe', tr: 'Kar Küresi' }, v: 40 },
  robot:    { d: 'north', i: '🤖', n: { en: 'Tin Robot', tr: 'Teneke Robot' }, v: 70 },
  vinyl:    { d: 'north', i: '💿', n: { en: 'Vinyl Record', tr: 'Plak' }, v: 55 },
  spoon:    { d: 'north', i: '🥄', n: { en: 'Silver Spoon', tr: 'Gümüş Kaşık' }, v: 50 },
  medal:    { d: 'east', i: '🎖️', n: { en: 'War Medal', tr: 'Savaş Madalyası' }, v: 80 },
  key:      { d: 'east', i: '🗝️', n: { en: 'Brass Key', tr: 'Pirinç Anahtar' }, v: 40 },
  watch:    { d: 'east', i: '⌚', n: { en: 'Pocket Watch', tr: 'Cep Saati' }, v: 90 },
  map:      { d: 'east', i: '🗺️', n: { en: 'Old City Map', tr: 'Eski Şehir Haritası' }, v: 60 },
  cartridge: { d: 'south', i: '🎮', n: { en: 'Retro Cartridge', tr: 'Retro Kartuş' }, v: 75 },
  pager:    { d: 'south', i: '📟', n: { en: 'Pager', tr: 'Çağrı Cihazı' }, v: 35 },
  handheld: { d: 'south', i: '🕹️', n: { en: 'Handheld Console', tr: 'El Konsolu' }, v: 95 },
  camera:   { d: 'south', i: '📷', n: { en: 'Film Camera', tr: 'Film Makinesi' }, v: 85 },
  jade:     { d: 'west', i: '🗿', n: { en: 'Jade Figurine', tr: 'Yeşim Heykelcik' }, v: 140 },
  ring:     { d: 'west', i: '💍', n: { en: 'Golden Ring', tr: 'Altın Yüzük' }, v: 150 },
  radio:    { d: 'west', i: '📻', n: { en: 'Antique Radio', tr: 'Antika Radyo' }, v: 110 },
  crown:    { d: 'west', i: '👑', n: { en: 'Costume Crown', tr: 'Kostüm Tacı' }, v: 120 },
};
const SETS = {
  center: { n: { en: 'Street Treasures', tr: 'Sokak Hazineleri' }, b: { en: '+10% search speed', tr: '+%10 arama hızı' } },
  north:  { n: { en: 'Suburban Memories', tr: 'Banliyö Anıları' }, b: { en: '+10 kg capacity', tr: '+10 kg kapasite' } },
  east:   { n: { en: 'Industrial Relics', tr: 'Sanayi Kalıntıları' }, b: { en: '+15% machine speed', tr: '+%15 makine hızı' } },
  south:  { n: { en: 'Digital Fossils', tr: 'Dijital Fosiller' }, b: { en: '+10% sell prices', tr: '+%10 satış fiyatı' } },
  west:   { n: { en: 'Downtown Riches', tr: 'Merkez Zenginlikleri' }, b: { en: '+25% XP', tr: '+%25 XP' } },
};

const PERKS = {
  quick:   { i: '✋', max: 5, n: { en: 'Quick Hands', tr: 'Çevik Eller' }, d: { en: '+10% search speed per rank', tr: 'Seviye başına +%10 arama hızı' } },
  mule:    { i: '🐴', max: 5, n: { en: 'Pack Mule', tr: 'Yük Katırı' }, d: { en: '+5 kg capacity per rank', tr: 'Seviye başına +5 kg kapasite' } },
  stomach: { i: '🍖', max: 3, n: { en: 'Iron Stomach', tr: 'Demir Mide' }, d: { en: '-12% hunger & thirst drain, less sickness', tr: '-%12 açlık/susuzluk, daha az hastalık' } },
  haggle:  { i: '🤝', max: 5, n: { en: 'Haggler', tr: 'Pazarlıkçı' }, d: { en: '+4% sell prices per rank', tr: 'Seviye başına +%4 satış fiyatı' } },
  luck:    { i: '🍀', max: 5, n: { en: 'Lucky Eye', tr: 'Şanslı Göz' }, d: { en: '+20% rare & collectible chance', tr: '+%20 nadir ve koleksiyon şansı' } },
  engineer:{ i: '🛠️', max: 5, n: { en: 'Engineer', tr: 'Mühendis' }, d: { en: '+10% machine speed per rank', tr: 'Seviye başına +%10 makine hızı' } },
  owl:     { i: '🦉', max: 3, n: { en: 'Night Owl', tr: 'Gece Kuşu' }, d: { en: 'Bigger light, dogs notice you later', tr: 'Daha geniş ışık, köpekler geç fark eder' } },
  tough:   { i: '💪', max: 5, n: { en: 'Tough Skin', tr: 'Kalın Deri' }, d: { en: '+10 max health per rank', tr: 'Seviye başına +10 maks. sağlık' } },
  runner:  { i: '👟', max: 3, n: { en: 'Marathon', tr: 'Maratoncu' }, d: { en: '+4% speed, -20% sprint cost per rank', tr: '+%4 hız, -%20 koşu maliyeti' } },
};

const GOALS = [
  { id: 'roof', i: '🏚️', n: { en: 'Patch the Shelter Roof', tr: 'Barınağın Çatısını Onar' }, cash: 150, cost: { steel: 6, pellets: 6 },
    b: { en: '+15 max energy after sleep, rain no longer soaks you', tr: 'Uykudan sonra +15 enerji, yağmur seni ıslatmaz' } },
  { id: 'phone', i: '📱', n: { en: 'Buy a Used Phone', tr: 'İkinci El Telefon Al' }, cash: 400, cost: {},
    b: { en: 'Sell remotely from anywhere (85% price)', tr: 'Her yerden uzaktan sat (%85 fiyat)' } },
  { id: 'license', i: '📜', n: { en: 'Scrap Dealer License', tr: 'Hurdacı Ruhsatı' }, cash: 1500, cost: { bale: 10, alu: 10 },
    b: { en: '+15% all sell prices', tr: 'Tüm satışlara +%15' } },
  { id: 'van', i: '🚐', n: { en: 'Fix Up an Old Van', tr: 'Eski Bir Minibüs Tamir Et' }, cash: 3000, cost: { steel: 15, crumb: 8, lithium: 4 },
    b: { en: 'Fast travel between base and district gates', tr: 'Üs ve bölge kapıları arasında hızlı seyahat' } },
  { id: 'workshop', i: '🏭', n: { en: 'Rent a Real Workshop', tr: 'Gerçek Bir Atölye Kirala' }, cash: 6000, cost: { steel: 20, cuingot: 10, components: 8 },
    b: { en: 'All machines +50% speed', tr: 'Tüm makineler +%50 hız' } },
  { id: 'plant', i: '♻️', n: { en: 'Found "Urban Scrap Co."', tr: '"Urban Scrap A.Ş."yi Kur' }, cash: 20000, cost: { alu: 40, steel: 60, cuingot: 30, components: 25, pellets: 80 },
    b: { en: 'You made it! +$300 passive income every morning', tr: 'Başardın! Her sabah +$300 pasif gelir' } },
];

// Main quest chain. c(S) => [current, needed]
const QUESTS = [
  { id: 'search', n: { en: 'Search a trash bag outside the south exit (press E)', tr: 'Güney çıkışının önündeki çöp poşetini ara (E\'ye bas)' }, c: S => [st(S, 's_trashbag'), 1], r: { cash: 5, xp: 10 } },
  { id: 'plastic', n: { en: 'Collect 8 plastic bottles', tr: '8 plastik şişe topla' }, c: S => [st(S, 'got_plastic'), 8], r: { xp: 15 } },
  { id: 'sell', n: { en: 'Sell scrap to Rusty (dealer, across the street from base)', tr: 'Hurdayı Rıza\'ya sat (üssün karşısındaki hurdacı)' }, c: S => [st(S, 'sales'), 1], r: { xp: 20 } },
  { id: 'eat', n: { en: 'Eat or drink something (press 1 / 2)', tr: 'Bir şey ye veya iç (1 / 2 tuşu)' }, c: S => [st(S, 'consumed'), 1], r: { xp: 10 } },
  { id: 'scrap', n: { en: 'Collect 5 scrap metal (dumpsters)', tr: '5 hurda demir topla (konteynerler)' }, c: S => [st(S, 'got_scrap'), 5], r: { xp: 20 } },
  { id: 'crowbar', n: { en: 'Craft a Crowbar at the workbench', tr: 'Tezgahta bir Levye yap' }, c: S => [S.tools.crowbar ? 1 : 0, 1], r: { cash: 10, xp: 30 } },
  { id: 'vending', n: { en: 'Pry open a vending machine', tr: 'Bir otomatı kanırtarak aç' }, c: S => [st(S, 's_vending'), 1], r: { xp: 25 } },
  { id: 'shredder', n: { en: 'Build a Plastic Shredder (blueprint spots at base)', tr: 'Plastik Kırıcı inşa et (üsteki taslak yerleri)' }, c: S => [S.builds.shredder ? 1 : 0, 1], r: { xp: 40 } },
  { id: 'pellets', n: { en: 'Collect 10 plastic pellets from the shredder', tr: 'Kırıcıdan 10 plastik granül topla' }, c: S => [st(S, 'made_pellets'), 10], r: { cash: 20, xp: 40 } },
  { id: 'sleep', n: { en: 'Sleep in your bed (after 18:00)', tr: 'Yatağında uyu (18:00\'den sonra)' }, c: S => [st(S, 'slept'), 1], r: { xp: 30 } },
  { id: 'smelter', n: { en: 'Build the Scrap Smelter', tr: 'Hurda Ocağını inşa et' }, c: S => [S.builds.smelter ? 1 : 0, 1], r: { xp: 50 } },
  { id: 'steel', n: { en: 'Smelt 4 steel plates', tr: '4 çelik levha erit' }, c: S => [st(S, 'made_steel'), 4], r: { xp: 40 } },
  { id: 'wrench', n: { en: 'Craft a Wrench', tr: 'Bir İngiliz Anahtarı yap' }, c: S => [S.tools.wrench ? 1 : 0, 1], r: { cash: 20, xp: 50 } },
  { id: 'north', n: { en: 'Explore the Old Suburbs (north)', tr: 'Eski Banliyö\'yü keşfet (kuzey)' }, c: S => [S.visited.north ? 1 : 0, 1], r: { xp: 40 } },
  { id: 'house', n: { en: 'Search an abandoned house', tr: 'Terk edilmiş bir evi ara' }, c: S => [st(S, 's_house'), 1], r: { xp: 50 } },
  { id: 'backpack', n: { en: 'Craft a Backpack', tr: 'Sırt Çantası yap' }, c: S => [bagCapOf(S) >= 25 ? 1 : 0, 1], r: { xp: 50 } },
  { id: 'tirecutter', n: { en: 'Build the Rubber Cutter', tr: 'Kauçuk Kesiciyi inşa et' }, c: S => [S.builds.tirecutter ? 1 : 0, 1], r: { xp: 50 } },
  { id: 'cutters', n: { en: 'Craft Bolt Cutters', tr: 'Cıvata Makası yap' }, c: S => [S.tools.cutters ? 1 : 0, 1], r: { cash: 40, xp: 80 } },
  { id: 'gateE', n: { en: 'Cut open the Industrial gate (east)', tr: 'Sanayi kapısını kes (doğu)' }, c: S => [S.flags.gate_east ? 1 : 0, 1], r: { xp: 80 } },
  { id: 'copper', n: { en: 'Build a Wire Stripper & make 5 copper ingots', tr: 'Kablo Soyucu kur ve 5 bakır külçe yap' }, c: S => [st(S, 'made_cuingot'), 5], r: { cash: 50, xp: 100 } },
  { id: 'respirator', n: { en: 'Craft a Respirator', tr: 'Gaz Maskesi yap' }, c: S => [S.gear.respirator ? 1 : 0, 1], r: { xp: 100 } },
  { id: 'south', n: { en: 'Explore the E-Waste Dump (south)', tr: 'E-Atık Çöplüğünü keşfet (güney)' }, c: S => [S.visited.south ? 1 : 0, 1], r: { xp: 80 } },
  { id: 'ebench', n: { en: 'Build the E-Waste Bench', tr: 'E-Atık Tezgahını kur' }, c: S => [S.builds.ebench ? 1 : 0, 1], r: { xp: 120 } },
  { id: 'headlamp', n: { en: 'Craft a Headlamp', tr: 'Kafa Lambası yap' }, c: S => [S.gear.headlamp ? 1 : 0, 1], r: { xp: 120 } },
  { id: 'grinder', n: { en: 'Craft an Angle Grinder', tr: 'Avuç Taşlama yap' }, c: S => [S.tools.grinder ? 1 : 0, 1], r: { cash: 100, xp: 200 } },
  { id: 'gateW', n: { en: 'Cut through the Downtown barricade (west)', tr: 'Merkez barikatını kes (batı)' }, c: S => [S.flags.gate_west ? 1 : 0, 1], r: { xp: 150 } },
  { id: 'atm', n: { en: 'Crack open an old ATM downtown', tr: 'Merkezde eski bir ATM\'yi kes' }, c: S => [st(S, 's_atm'), 1], r: { xp: 150 } },
  { id: 'roof', n: { en: 'Life Goal: Patch the Shelter Roof (Journal)', tr: 'Hayat Hedefi: Çatıyı Onar (Günlük)' }, c: S => [S.goals.roof ? 1 : 0, 1], r: { xp: 100 } },
  { id: 'col10', n: { en: 'Find 10 different collectibles', tr: '10 farklı koleksiyon eşyası bul' }, c: S => [Object.keys(S.collection).length, 10], r: { cash: 200, xp: 200 } },
  { id: 'license', n: { en: 'Life Goal: Get a Scrap Dealer License', tr: 'Hayat Hedefi: Hurdacı Ruhsatı Al' }, c: S => [S.goals.license ? 1 : 0, 1], r: { xp: 250 } },
  { id: 'van', n: { en: 'Life Goal: Fix Up an Old Van', tr: 'Hayat Hedefi: Minibüsü Tamir Et' }, c: S => [S.goals.van ? 1 : 0, 1], r: { xp: 300 } },
  { id: 'col20', n: { en: 'Complete the whole collection (20)', tr: 'Tüm koleksiyonu tamamla (20)' }, c: S => [Object.keys(S.collection).length, 20], r: { cash: 1000, xp: 500 } },
  { id: 'plant', n: { en: 'Life Goal: Found "Urban Scrap Co."', tr: 'Hayat Hedefi: "Urban Scrap A.Ş."yi Kur' }, c: S => [S.goals.plant ? 1 : 0, 1], r: { xp: 1000 } },
];
function st(S, k) { return S.stats[k] || 0; }
function bagCapOf(S) { return S.gear.bag ? CRAFT[S.gear.bag].cap : 12; }

const WEATHER = {
  clear:  { i: '☀️', n: { en: 'Clear', tr: 'Açık' } },
  cloudy: { i: '☁️', n: { en: 'Cloudy', tr: 'Bulutlu' } },
  rain:   { i: '🌧️', n: { en: 'Rain', tr: 'Yağmurlu' } },
  heat:   { i: '🥵', n: { en: 'Heatwave', tr: 'Sıcak Hava Dalgası' } },
};
